name: use reusable
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: using reusable workflow
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Use reusable workflow
              uses: ./.github/workflows/reusable-workflows.yml

            - name: Show data
              run: echo "hello there"