name: use reusable
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: using reusable workflow
jobs:
    build:
        uses: ./.github/workflows/reusable-workflows.yml