name: use reusable
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: using reusable workflow
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: use reusable workflow
              uses: ./.github/workflows/pipeline.yml
            - name: show data
              run: echo "hello there"