name: reusable workflow
on: 
    workflow_call:
        inputs:
            artifact-name: 
                description: name of the deployable artifact files
                required: false #Set to true if you want the workflow to fail if this value is not provided
                default: dist
                type: string     
run-name: reusable workflows
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get files
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifact-name }}
            - name: Show files
              run: ls -lrt shared/
