name: use reusable
on: 
    push: 
        branches:
            - main
    workflow_dispatch:
run-name: using reusable workflow
jobs:
    upload-artifacts:
        runs-on: ubuntu-latest
        steps:
            - name: Create files
              run: |
                mkdir shared
                cd shared
                echo "this is file 1" >> file1.txt
                echo "this is file 1" >> file2.txt
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: shared-files
                path: |
                    shared
                
    build:
        needs:
            - upload-artifacts
        uses: ./.github/workflows/reusable-workflows.yml
        with:
            artifact-name: shared-files
        {# secrets:
            aws-instance-id: ${{ secrets.aws-instance-id }} #}
    print-usable-workflow-outputs:
        needs:
            deploy
        runs-on: ubuntu-latest
        steps:
            - name: Print build output
              run: echo ${{ needs.deploy.outputs.result }}

